spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

########## MSSQL ##########
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=btcstore
spring.datasource.password=M4@uC9!sW#2qL7yP
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=btc-store;encrypt=true;trustServerCertificate=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.default_schema=store
########## MSSQL ##########